[package]
name = "helve-world-runtime"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
helve-types = { path = "../../helve-types" }
helve-world-chunk = { path = "../helve-world-chunk" }
helve-world-contract = { path = "../helve-world-contract" }

[dev-dependencies]
helve-world-reference = { path = "../helve-world-reference" }

[lints]
workspace = true
