[package]
name = "crucible-server"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
crucible-connection-core = { path = "../network/crucible-connection-core" }
crucible-connection-driver = { path = "../network/crucible-connection-driver" }
crucible-packet-core = { path = "../network/crucible-packet-core" }
crucible-preplay-core = { path = "../network/crucible-preplay-core" }
crucible-preplay-io = { path = "../network/crucible-preplay-io" }
crucible-publication-core = { path = "../network/crucible-publication-core" }
crucible-session-core = { path = "../network/crucible-session-core" }
crucible-target-26-2 = { path = "../network/crucible-target-26-2" }

[lints]
workspace = true
