//! @generated by `tools/stored_state_lookup.py` 0.3.0; do not edit by hand.
//! Exact cold persisted-state lookup metadata for Minecraft Java 26.2.

pub(crate) const STORED_STATE_LOOKUP_BYTES: usize = 416_665;
pub(crate) const STORED_STATE_LOOKUP_COUNT: usize = 32_366;
pub(crate) const STORED_STATE_BUCKET_COUNT: usize = 8_192;
pub(crate) const STORED_STATE_BUCKET_MASK: u64 = 8_191;
pub(crate) const STORED_STATE_SLOT_COUNT: usize = 32_768;
pub(crate) const STORED_STATE_SLOT_MASK: u64 = 32_767;
pub(crate) const STORED_STATE_NAME_COUNT: usize = 1_196;
pub(crate) const STORED_STATE_PROPERTY_PAIR_COUNT: usize = 435;
pub(crate) const STORED_STATE_PROPERTY_OCCURRENCES: usize = 145_577;
pub(crate) const STORED_STATE_MAX_PROPERTIES: usize = 7;
pub(crate) const STORED_STATE_DISPLACEMENTS_OFFSET: usize = 0;
pub(crate) const STORED_STATE_SLOTS_OFFSET: usize = 16_384;
pub(crate) const STORED_STATE_DESCRIPTORS_OFFSET: usize = 81_920;
pub(crate) const STORED_STATE_PROPERTY_IDS_OFFSET: usize = 211_384;
pub(crate) const STORED_STATE_NAME_INDEX_OFFSET: usize = 375_160;
pub(crate) const STORED_STATE_PAIR_INDEX_OFFSET: usize = 378_748;
pub(crate) const STORED_STATE_NAME_BLOB_OFFSET: usize = 380_488;
pub(crate) const STORED_STATE_PAIR_BLOB_OFFSET: usize = 411_283;

pub(crate) static STORED_STATE_LOOKUP_DATA: &[u8; STORED_STATE_LOOKUP_BYTES] =
    include_bytes!("generated/26.2-stored-state-lookup.bin");
