//! @generated by `tools/stored_state_lookup.py` 0.3.0; do not edit by hand.
//! Exact cold persisted-state lookup metadata for Minecraft Java 26.2.

pub(crate) const STORED_STATE_LOOKUP_INPUT_SHA256: &str = "2cbdfa96881be3f47dee8afdb5c4006e42cf2a718c440bf8ae76761a6acd31af";
pub(crate) const STORED_STATE_LOOKUP_BINARY_SHA256: &str = "da3050ec355349d4ec448be1a44d443dc57dc170d58c9b4f6cb17bd8e986f758";
pub(crate) const STORED_STATE_LOOKUP_BYTES: usize = 416665;
pub(crate) const STORED_STATE_LOOKUP_COUNT: usize = 32366;
pub(crate) const STORED_STATE_BUCKET_COUNT: usize = 8192;
pub(crate) const STORED_STATE_BUCKET_MASK: u64 = 8191;
pub(crate) const STORED_STATE_SLOT_COUNT: usize = 32768;
pub(crate) const STORED_STATE_SLOT_MASK: u64 = 32767;
pub(crate) const STORED_STATE_NAME_COUNT: usize = 1196;
pub(crate) const STORED_STATE_PROPERTY_PAIR_COUNT: usize = 435;
pub(crate) const STORED_STATE_PROPERTY_OCCURRENCES: usize = 145577;
pub(crate) const STORED_STATE_MAX_PROPERTIES: usize = 7;
pub(crate) const STORED_STATE_DISPLACEMENTS_OFFSET: usize = 0;
pub(crate) const STORED_STATE_SLOTS_OFFSET: usize = 16384;
pub(crate) const STORED_STATE_DESCRIPTORS_OFFSET: usize = 81920;
pub(crate) const STORED_STATE_PROPERTY_IDS_OFFSET: usize = 211384;
pub(crate) const STORED_STATE_NAME_INDEX_OFFSET: usize = 375160;
pub(crate) const STORED_STATE_PAIR_INDEX_OFFSET: usize = 378748;
pub(crate) const STORED_STATE_NAME_BLOB_OFFSET: usize = 380488;
pub(crate) const STORED_STATE_PAIR_BLOB_OFFSET: usize = 411283;

pub(crate) static STORED_STATE_LOOKUP_DATA: &[u8; STORED_STATE_LOOKUP_BYTES] =
    include_bytes!("generated/26.2-stored-state-lookup.bin");
