[package]
name = "crucible-section-qualification"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[dependencies]
crucible-generated = { path = "../../data/crucible-generated" }
crucible-world-contract = { path = "../../world/crucible-world-contract" }
crucible-world-reference = { path = "../../world/crucible-world-reference" }
crucible-world-section = { path = "../../world/crucible-world-section" }

[lints]
workspace = true
