[package]
name = "helve-preplay-core"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
helve-connection-core = { path = "../helve-connection-core" }
helve-connection-driver = { path = "../helve-connection-driver" }
helve-publication-core = { path = "../helve-publication-core" }
helve-session-core = { path = "../helve-session-core" }

[dev-dependencies]
helve-packet-core = { path = "../helve-packet-core" }

[lints]
workspace = true
