[package]
name = "xtask"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[dependencies]
crucible-section-qualification = { path = "../../crates/qualification/crucible-section-qualification" }
crucible-section-vanilla-fixture = { path = "../../crates/qualification/crucible-section-vanilla-fixture" }

[lints]
workspace = true
