[package]
name = "crucible-world-access-qualification"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
crucible-benchmark-support = { path = "../crucible-benchmark-support" }
crucible-generated = { path = "../../data/crucible-generated" }
crucible-types = { path = "../../crucible-types" }
crucible-world-chunk = { path = "../../world/crucible-world-chunk" }
crucible-world-reference = { path = "../../world/crucible-world-reference" }

[lints]
workspace = true
