#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import state_data

SCHEMA = 1
GENERATOR_VERSION = "0.2.0"
HASH_ALGORITHM = "fnv1a64-canonical-state-key-v1"
FNV_OFFSET_BASIS = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3
MAX_U16 = (1 << 16) - 1
MAX_U32 = (1 << 32) - 1


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def canonical_state_fingerprint(key: str) -> int:
    value = FNV_OFFSET_BASIS
    for byte in key.encode("utf-8"):
        value ^= byte
        value = (value * FNV_PRIME) & 0xFFFF_FFFF_FFFF_FFFF
    return value


def rust_string(value: str) -> str:
    parts = ['"']
    for char in value:
        code = ord(char)
        if char == "\\":
            parts.append("\\\\")
        elif char == '"':
            parts.append('\\"')
        elif char == "\n":
            parts.append("\\n")
        elif char == "\r":
            parts.append("\\r")
        elif char == "\t":
            parts.append("\\t")
        elif 0x20 <= code <= 0x7E:
            parts.append(char)
        else:
            parts.append(f"\\u{{{code:x}}}")
    parts.append('"')
    return "".join(parts)


def load_manifest(path: Path) -> dict[str, object]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("state-data manifest root must be an object")
    return value


def render_rust(
    data: dict[str, object], manifest: dict[str, object]
) -> tuple[str, dict[str, object]]:
    state_data.validate(data)
    input_digest = state_data.digest(data)
    if manifest.get("input_digest") != input_digest:
        raise ValueError("qualified input digest does not match state-data manifest")

    assignment = manifest.get("assignment_policy")
    if not isinstance(assignment, str):
        raise ValueError("state-data manifest is missing assignment_policy")
    raw_states = data["states"]
    assert isinstance(raw_states, list)
    states = state_data.assign(raw_states, assignment)
    if manifest.get("state_count") != len(states):
        raise ValueError("state count differs from state-data manifest")
    if len(states) > MAX_U16 + 1:
        raise ValueError(
            "stored-state lookup v1 requires a target universe addressable by u16 state IDs"
        )

    state_generation = manifest.get("generation_digest")
    if not isinstance(state_generation, str) or len(state_generation) != 64:
        raise ValueError("state-data manifest has invalid generation_digest")

    rows: list[tuple[int, str, int]] = []
    for state_id, state in enumerate(states):
        key = str(state["key"])
        rows.append((canonical_state_fingerprint(key), key, state_id))
    rows.sort(key=lambda row: (row[0], row[1]))

    key_blob_parts: list[str] = []
    fingerprints: list[int] = []
    metadata: list[tuple[int, int, int]] = []
    offset = 0
    max_key_bytes = 0
    for fingerprint, key, state_id in rows:
        encoded = key.encode("utf-8")
        key_len = len(encoded)
        if key_len > MAX_U16:
            raise ValueError(f"state key exceeds u16 byte length: {key}")
        if offset > MAX_U32 or offset + key_len > MAX_U32:
            raise ValueError("stored state key blob exceeds u32 address space")
        if state_id > MAX_U16:
            raise ValueError("stored state ID exceeds u16")
        fingerprints.append(fingerprint)
        metadata.append((offset, key_len, state_id))
        key_blob_parts.append(key)
        offset += key_len
        max_key_bytes = max(max_key_bytes, key_len)

    key_blob = "".join(key_blob_parts)
    lines = [
        f"//! @generated by `tools/stored_state_lookup.py` {GENERATOR_VERSION}; do not edit by hand.",
        "//! Cold exact persisted block-state lookup for the pinned target.",
        "",
        "use crate::state_lookup::StoredStateLookupRow;",
        "",
        f'pub const STORED_STATE_LOOKUP_INPUT_SHA256: &str = "{input_digest}";',
        f'pub const STORED_STATE_DATA_GENERATION_SHA256: &str = "{state_generation}";',
        f'pub const STORED_STATE_LOOKUP_HASH_ALGORITHM: &str = "{HASH_ALGORITHM}";',
        f"pub const STORED_STATE_LOOKUP_COUNT: usize = {len(metadata)};",
        f"pub const STORED_STATE_KEY_BLOB_BYTES: usize = {len(key_blob.encode('utf-8'))};",
        f"pub const STORED_STATE_MAX_KEY_BYTES: usize = {max_key_bytes};",
        f"pub static STORED_STATE_KEY_BLOB: &str = {rust_string(key_blob)};",
        "pub static STORED_STATE_FINGERPRINTS: [u64; STORED_STATE_LOOKUP_COUNT] = [",
    ]
    for fingerprint in fingerprints:
        lines.append(f"    0x{fingerprint:016x},")
    lines.extend(
        [
            "];",
            "pub static STORED_STATE_ROWS: [StoredStateLookupRow; STORED_STATE_LOOKUP_COUNT] = [",
        ]
    )
    for key_offset, key_len, state_id in metadata:
        lines.append(
            "    StoredStateLookupRow::new("
            f"{key_offset}, {key_len}, {state_id}),"
        )
    lines.extend(
        [
            "];",
            "",
            "#[cfg(test)]",
            "mod tests {",
            "    use super::*;",
            "",
            "    #[test]",
            "    fn generated_lookup_ranges_and_order_hold() {",
            "        assert_eq!(STORED_STATE_FINGERPRINTS.len(), STORED_STATE_LOOKUP_COUNT);",
            "        assert_eq!(STORED_STATE_ROWS.len(), STORED_STATE_LOOKUP_COUNT);",
            "        assert_eq!(STORED_STATE_KEY_BLOB.len(), STORED_STATE_KEY_BLOB_BYTES);",
            "        assert!(STORED_STATE_FINGERPRINTS.windows(2).all(|pair| pair[0] <= pair[1]));",
            "        for row in STORED_STATE_ROWS {",
            "            let start = usize::try_from(row.key_offset()).expect(\"generated offset fits usize\");",
            "            let end = start + usize::from(row.key_len());",
            "            assert!(STORED_STATE_KEY_BLOB.get(start..end).is_some());",
            "        }",
            "    }",
            "}",
            "",
        ]
    )
    code = "\n".join(lines)

    result_manifest: dict[str, object] = {
        "schema": SCHEMA,
        "generator_version": GENERATOR_VERSION,
        "hash_algorithm": HASH_ALGORITHM,
        "layout": "soa-u64-fingerprint-u32-offset-u16-length-u16-state-v1",
        "target": manifest.get("target"),
        "state_count": len(metadata),
        "assignment_policy": assignment,
        "state_data_input_sha256": input_digest,
        "state_data_generation_sha256": state_generation,
        "key_blob_bytes": len(key_blob.encode("utf-8")),
        "max_key_bytes": max_key_bytes,
        "fingerprint_bytes": len(fingerprints) * 8,
        "metadata_bytes": len(metadata) * 8,
        "rust_sha256": sha256_text(code),
    }
    result_manifest["lookup_digest"] = state_data.digest(result_manifest)
    return code, result_manifest


def rendered_manifest(value: dict[str, object]) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def command_inspect(args: argparse.Namespace) -> int:
    data = state_data.load(Path(args.input))
    manifest = load_manifest(Path(args.state_manifest))
    _, result = render_rust(data, manifest)
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


def command_generate(args: argparse.Namespace) -> int:
    data = state_data.load(Path(args.input))
    manifest = load_manifest(Path(args.state_manifest))
    code, result = render_rust(data, manifest)
    output = Path(args.output)
    result_path = Path(args.manifest)
    output.parent.mkdir(parents=True, exist_ok=True)
    result_path.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(code, encoding="utf-8")
    result_path.write_text(rendered_manifest(result), encoding="utf-8")
    print(
        f"generated {result['state_count']} cold state keys / "
        f"{result['key_blob_bytes']} UTF-8 bytes / "
        f"{result['fingerprint_bytes'] + result['metadata_bytes']} index bytes"
    )
    return 0


def command_verify(args: argparse.Namespace) -> int:
    data = state_data.load(Path(args.input))
    manifest = load_manifest(Path(args.state_manifest))
    code, result = render_rust(data, manifest)
    expected_manifest = rendered_manifest(result)
    ok = True
    for path, expected in (
        (Path(args.output), code),
        (Path(args.manifest), expected_manifest),
    ):
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            print(f"stale generated file: {path}", file=sys.stderr)
            ok = False
    return 0 if ok else 1


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Helve cold stored block-state lookup generator"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    for name, handler in {
        "inspect": command_inspect,
        "generate": command_generate,
        "verify": command_verify,
    }.items():
        subparser = subparsers.add_parser(name)
        subparser.add_argument("input")
        subparser.add_argument(
            "--state-manifest",
            default="vanilla/state-data/26.2-state-data-manifest.json",
        )
        if name in {"generate", "verify"}:
            subparser.add_argument("--output", required=True)
            subparser.add_argument("--manifest", required=True)
        subparser.set_defaults(handler=handler)
    args = parser.parse_args()
    try:
        return int(args.handler(args))
    except (KeyError, OSError, ValueError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
