[package]
name = "helve-world-import"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
helve-generated = { path = "../../data/helve-generated" }
helve-types = { path = "../../helve-types" }
miniz_oxide = { version = "=0.8.9", default-features = false }

[lints]
workspace = true
